version: "3.8"

services:
  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - mynetwork
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    #  REMOVE THIS IN PRODUCTION
    # ports:
    #   - "5432:5432"

networks:
  mynetwork:

volumes:
  pgdata: